import { JSDOM } from 'jsdom';
import fs from 'fs';
const dom = new JSDOM(fs.readFileSync('/home/claude/forge/dist/色阶发生器.html','utf8'),
  { runScripts:'dangerously', pretendToBeVisual:true, url:'https://x/' });
const { window } = dom; const d = window.document;
await new Promise(r=>setTimeout(r,200));
const click = s => d.querySelector(s).dispatchEvent(new window.MouseEvent('click',{bubbles:true}));
const err=[];
const brand = () => [...d.querySelectorAll('#brand .seg-cell')];
if (brand().length!==10) err.push('brand cells '+brand().length);
if (d.querySelectorAll('#neutral .seg-cell').length!==14) err.push('neutral cells');
if (d.querySelectorAll('#cvd button').length!==5) err.push('cvd buttons');
if (d.querySelectorAll('#presets button').length!==6) err.push('presets');
console.log('caption:', d.querySelector('#caption').textContent);
console.log('light  :', brand().map(b=>b.dataset.copy.slice(1)).join(' '));
click('[data-mode="dark"]');
console.log('dark   :', brand().map(b=>b.dataset.copy.slice(1)).join(' '));
console.log('html mode:', d.documentElement.getAttribute('data-mode'));
click('[data-cvd="deuteranopia"]');
const shown = brand().map(b=>b.getAttribute('style').match(/--c:(#[0-9A-F]{6})/)[1]);
console.log('cvd shown:', shown.join(' ').slice(0,80)+'…');
console.log('cvd copy unchanged:', brand()[0].dataset.copy);
if (new Set(shown).size !== 10) err.push('cvd collapsed to '+new Set(shown).size);
click('[data-cvd="none"]'); click('[data-mode="light"]');
click('[data-set="#00A870"]');
console.log('preset :', d.querySelector('#hex').value, brand()[6].dataset.copy);
const inp = d.querySelector('#hex');
inp.value='rgb(0, 82, 217)'; inp.dispatchEvent(new window.Event('input',{bubbles:true}));
console.log('rgb in :', brand()[6].dataset.copy, '| hint:', JSON.stringify(d.querySelector('#hint').textContent));
inp.value='garbage'; inp.dispatchEvent(new window.Event('input',{bubbles:true}));
console.log('bad in : entry.class=', d.querySelector('#entry').className, '| hint:', d.querySelector('#hint').textContent);
console.log('\nERRORS:', err.length?err:'none');
process.exit(err.length?1:0);
