/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Backdrop: typeof import('./components/Backdrop.vue')['default']
    CvdCheck: typeof import('./components/CvdCheck.vue')['default']
    ExportPanel: typeof import('./components/ExportPanel.vue')['default']
    Gallery: typeof import('./components/Gallery.vue')['default']
    Inspirations: typeof import('./components/Inspirations.vue')['default']
    PresetLibrary: typeof import('./components/PresetLibrary.vue')['default']
    ProfilePanel: typeof import('./components/ProfilePanel.vue')['default']
    TAlert: typeof import('tdesign-vue-next')['Alert']
    TButton: typeof import('tdesign-vue-next')['Button']
    TColorPicker: typeof import('tdesign-vue-next')['ColorPicker']
    TDialog: typeof import('tdesign-vue-next')['Dialog']
    TDivider: typeof import('tdesign-vue-next')['Divider']
    TDrawer: typeof import('tdesign-vue-next')['Drawer']
    TEmpty: typeof import('tdesign-vue-next')['Empty']
    TInput: typeof import('tdesign-vue-next')['Input']
    TLoading: typeof import('tdesign-vue-next')['Loading']
    TPopconfirm: typeof import('tdesign-vue-next')['Popconfirm']
    TRadioButton: typeof import('tdesign-vue-next')['RadioButton']
    TRadioGroup: typeof import('tdesign-vue-next')['RadioGroup']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TSlider: typeof import('tdesign-vue-next')['Slider']
    TSpace: typeof import('tdesign-vue-next')['Space']
    TSwitch: typeof import('tdesign-vue-next')['Switch']
    TTag: typeof import('tdesign-vue-next')['Tag']
    TTooltip: typeof import('tdesign-vue-next')['Tooltip']
  }
}
